name: Integration Test

on:
  pull_request:
    types: [opened, syncronized, reopened]
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: |
         mkdir -p gui/frontend/dist
         touch gui/frontend/dist/index.html
         sudo apt update
         sudo apt install -y libpcap-dev
         env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=mod -tags headless .
         env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -mod=mod -tags headless .
         env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -mod=mod -tags headless .
         env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -mod=mod -tags headless .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run Go tests
        run: |
          mkdir -p gui/frontend/dist
          touch gui/frontend/dist/index.html
          sudo apt update
          sudo apt upgrade -y libpcap-dev
          go test  -tags headless -mod=mod ./... -v

  test-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: test gui
        run: |
          cd gui/frontend
          npm ci
          npm run test

  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run static checks
        run: |
          mkdir -p gui/frontend/dist
          touch gui/frontend/dist/index.html
          sudo apt update
          go install honnef.co/go/tools/cmd/staticcheck@latest
          { ~/go/bin/staticcheck  ./... ; }

  linux-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: build gui
        run: |
          sudo apt update
          sudo apt install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libpcap-dev
          cd gui/frontend
          npm ci
          npm run build
          cd ../..
          go build -tags desktop,production -ldflags "-w -s"

  darwin-gui:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: netclient
          build-platform: darwin/universal
          package: false
          go-version: 1.19
          node-version: 19.x

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: build gui
        run: |
          cd gui/frontend
          npm ci
          npm run build
          cd ../..
          go build -tags desktop,production -ldflags "-w -s -H windowsgui"
